//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SagarPractical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public int playerid { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> totalmatchesplayed { get; set; }
        public string contactnumber { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dateofBirth { get; set; }
        public Nullable<decimal> playerheight { get; set; }
        public Nullable<decimal> playerweight { get; set; }
        public Nullable<int> role { get; set; }
        public Nullable<bool> isselected { get; set; }
        public Nullable<bool> flagdeleted { get; set; }
        public string password { get; set; }
    }
}
